version: "3.9"
services:
  mariadb:
    build:
      context: .
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-appdb}
      MARIADB_USER: ${MARIADB_USER:-appuser}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-apppass}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./conf.d:/etc/mysql/mariadb.conf.d:ro
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
